### ISSUE TITLE
Add installation script for docker file

### ISSUE THREAD

**Issue by joshuasamuelevans** [opengeos/whiteboxR#123]
Hi there, 

First of all thank you for all your hard work creating this package! Currently I am trying to build the docker image given the associated Dockerfile. However, there seems to be a dependency on an installation script that is not provided on line 41 so the image cannot be built locally (see below).

COPY misc/install.R /home/rstudio/

I know I am able to pull the image for docker hub but I would like to be able to take the Dockerfile and install additional dependencies that are needed within my workflow without having to download them within the container. Could you provide install.R or integrate the commands into the Dockerfile?

Thanks

**Comment by brownag** [comment]
The installation script is in misc folder of the GitHub repo--so it would require cloning the repository to build locally.

The install script was just a one-liner to install the WhiteboxTools binary, so in https://github.com/opengeos/whiteboxR/pull/124/commits/c504f56bbb8e46fecc107526cb8fe00d7e5c6ae3 I have moved the contents into the Rscript command in the Dockerfile. Now building the image will no longer require a local instance of the Git repository.
